version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:latest
    container_name: consul-server
    restart: always
    volumes:
     - ./server.json:/consul/config/server1.json:ro
     - ./certs/:/consul/config/certs/:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

 
networks:
  consul:
    driver: bridge

