version: '3'
services:
  eureka-discovery-service:
    image: openjdk:17-jdk-alpine
    container_name: eureka-discovery-service
    ports:
      - "8081:8081"
    volumes:
      - ./target:/app
    working_dir: /app
    command: ["java", "-jar", "EUREKA-Discovery-Service-0.0.1-SNAPSHOT.jar"]

